### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by QarthO** [PimvanderLoos/AnimatedArchitecture#637] opened 2023-11-23 15:52 UTC
Currently, a requirement is for the plugin to be on Java 19+, I'm assuming you're using a library that isn't available on previous versions. 

Later versions of mc are made and developed on and for Java 17. Minecraft is most optimized for this version. Requiring the server to be on Java 19 in order to use this plugin causes some issues.

I understand that lowering the minimum Java version is a big ask, but I do think it's definitely warranted. Would also let a lot more people be able to use this plugin since not everyone's willing to attempt to run their server on Java 19+

**Comment by PimvanderLoos** [comment] 2023-11-23 17:20
Duplicate of #556

**Closed as not planned by PimvanderLoos** 2023-11-23 17:20 UTC
