### ISSUE TITLE
GarageDoor bug - leave 1 block row

### ISSUE THREAD

**Issue by JaHollTV** [PimvanderLoos/AnimatedArchitecture#533] opened 2023-07-16 15:11 UTC
Newest AA-Release.

Hey there,

i created a new garage door. Everything was fine (i love the preview for the door!!).

The door open as expected:
![2023-07-16_17 08 41](https://github.com/PimvanderLoos/AnimatedArchitecture/assets/48917504/67a67913-8635-4bbe-974b-a2e9b367614e)

But when 1 close - 1 row of blocks is not moved
![2023-07-16_17 08 45](https://github.com/PimvanderLoos/AnimatedArchitecture/assets/48917504/0b0c8f19-4bd5-4362-8483-7c1db7c9961e)

No errors in the Console

**Comment by JaHollTV** [comment] 2023-07-16 15:38
![2023-07-16_17 36 37](https://github.com/PimvanderLoos/AnimatedArchitecture/assets/48917504/7a0e9531-690e-452e-9ab5-34aa4cd549b5)
Found out that AA thinks the door is at another position, as it realy is

**Comment by PimvanderLoos** [comment] 2023-07-23 10:55
Hey! I'm back from vacation, so I can finally work on a fix for this :)

~~It appears that it's an issue specifically with garage doors that are an even number of blocks tall :sweat_smile:. I'll have a fix ready soon, which will be part of the upcoming 0.6 release.~~

It looks like the issue isn't as straightforward as I had initially thought, and I have found some other issues with garage doors as well, so it's taking quite a bit longer than I'd anticipated. Due to other commitments, this makes it a little difficult to resolve it in a timely manner, but I'll try to have something as soon as possible.

**Comment by JaHollTV** [comment] 2023-09-16 04:56
Maybe you've already "accidentally" fixed it in your development branch and it just needs a new release?

**Comment by PimvanderLoos** [comment] 2023-09-16 08:29
I'm afraid that it's not really fixed in the latest builds of the dev branch. The more I worked on the garage doors, the more issues I found with it. Fixing the type is going to take more time than I currently have. I still consider this a very important issue, so I will try to find some time to work on it when I can.

**Comment by JaHollTV** [comment] 2024-02-25 15:30
Any update here?

We need Bigdors2 (AnimatedArchitecture) :)

**Comment by PimvanderLoos** [comment] 2024-03-09 11:51
Hey! I'm sorry it took so long, but I've finally got a fix out. It'll be merged into the master branch soon.

I'm not sure what `other issues with garage doors` I was referring to above, but as far as I can see, everything seems to work now. If you encounter any further issues, do let me know! Hopefully, I can resolve any future issues much, much faster than this one ;)

**Closed as completed** 2024-03-09 12:08 UTC
Labels: bug
